[build]
    command = "bower install"

[[redirects]]
    from = "/store.json"
    to = "https://cloud-emoticon-store-bridge.ktachibana.party/json"
    status = 200

[[redirects]]
    from = "/store"
    to = "https://cloud-emoticon-store-bridge.ktachibana.party"
    status = 200

[[redirects]]
    from = "/2"
    to = "https://cloudemoticon2-alpha.netlify.app"
    status = 301

# Plausible
[[redirects]]
from = "/js/script.js"
to = "https://plausible.io/js/plausible.js"
status = 200

[[redirects]]
from = "/api/event"
to = "https://plausible.io/api/event"
status = 200
